from db import conn,cursor
from etl import custDf,prodDf,storeDf,salesDf,factDf
from psycopg2.extras import execute_values

# creating customer table
def cust_table():
    with conn: 
        try:
            cursor.execute('''CREATE TABLE IF NOT EXISTS cust_table(
                            custId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            custName VARCHAR(20) NOT NULL,
                            email VARCHAR(30) NOT NULL,
                            city VARCHAR(10) NOT NULL,
                            source_custId INT);''')
            print('table created')
        except Exception as e:
            print("Table can't created ",e)

# inserting value in customer table
def insert_cust():
    query='''INSERT INTO cust_table(custname,email,city,source_custId) VALUES %s'''
    values=list(custDf.itertuples(index=False,name=None))
    with conn:
        try:
            execute_values(cursor,query,values)
            print('value inserted')
        except Exception as e:
            print("Value can't inserted",e)

# Creating prod table
def prod_table():
    with conn:
        try:
            cursor.execute('''CREATE TABLE IF NOT EXISTS prod_table(
                                prodId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                prodName TEXT NOT NULL,
                                category VARCHAR(20) NOT NULL,
                                costprice INT NOT NULL,
                                unitprice INT NOT NULL)''')
            print('Product table created')
        except Exception as e:
            print("Table can't be created because ",e)

# Inserting value into prod table
def insert_prod():
    query='''INSERT INTO prod_table(prodName,category,costprice,unitprice) VALUES %s'''
    values=list(prodDf.itertuples(index=False,name=None))
    with conn:
        try:
            execute_values(cursor,query,values)
            print('Value inserted in prod table')
        except Exception as e:
            print("Value is not inserted because ",e)

# Creating store table
def store_table():
    with conn:
        try:
            cursor.execute('''CREATE TABLE IF NOT EXISTS store_table(
                                storeId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                storeName TEXT NOT NULL,
                                region VARCHAR(10) NOT NULL,
                                city VARCHAR(10) NOT NULL);''')
            print('Store table created')
        except Exception as e:
            print('Store table cannot be created',e)
            
# Inserting store value
def insert_store():
    query='''INSERT INTO store_table(storeName,region,city) VALUES %s'''
    data=list(storeDf.itertuples(name=None,index=None))
    with conn:
        try:
            execute_values(cursor,query,data)
            print('Value inserted in store table')
        except Exception as e:
            print("Value doesn't inserted in store table")

# Creating order table
def order_table():
    with conn:
        try:
            cursor.execute('''CREATE TABLE IF NOT EXISTS order_table(
                                orderId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                custId INT REFERENCES cust_table(custId) ON DELETE CASCADE ON UPDATE CASCADE,
                                prodId INT REFERENCES prod_table(prodId) ON DELETE CASCADE ON UPDATE CASCADE,
                                storeId INT REFERENCES store_table(storeId) ON DELETE CASCADE ON UPDATE CASCADE,
                                quantity INT NOT NULL,
                                unitprice INT NOT NULL,
                                costprice INT NOT NULL,
                                revenue INT NOT NULL,
                                costamount INT NOT NULL,
                                profit INT NOT NULL,
                                order_date TIMESTAMPTZ);''')
            print('order table created')
        except Exception as e:
            print('order table is not created ',e)

# Insert into order table
def insert_order():
    query='''INSERT INTO order_table(custId,prodId,storeId,quantity,unitprice,costprice,revenue,costamount,profit,order_date) VALUES %s;'''
    values=list(factDf.itertuples(name=None,index=False))
    with conn:
        try:
            execute_values(cursor,query,values)
            print("Total rows in DF:", len(factDf))
            print("Total tuples prepared:", len(values))
            print('Value inserted into order table')
        except Exception as e:
            print('Value cannot be inserted ',e)
